name: Deploy on branch 01-ec2
run-name: "Deploy on branch 01-ec2"
on:
  push:
    branches: ["01-ec2"]

jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/01-ec2' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "Deploy on branch ${{ github.ref }}"

      - name: Display information
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "${{ github.actor }} deployed on branch ${{ env.BRANCH_NAME }} in repo ${{ github.repository }}"
